### ISSUE TITLE
IATI vocabulary codelists -are numbers "reserved"

### ISSUE THREAD

**Issue by stevieflow** [OpenAgFunding/development#18]
We'd like to understand how the numbering system for the various vobaulary codelists is operated - as this may have an impact in terms of piloting certain lists/contexts

**Comment by stevieflow** [comment]
Discussion underway on IATI Discuss: http://discuss.iatistandard.org/t/vocabulary-codelists-reserving-a-number/494/4

**Comment by stevieflow** [comment]
(some link to codelist criteria: https://github.com/OpenAgFunding/development/issues/16)

**Comment by timgdavies** [comment]
In http://discuss.iatistandard.org/t/vocabulary-codelists-reserving-a-number/494/4 IATI support agreed that numbers can be reserved.
