### ISSUE TITLE
ACTION: access a full list of the FAOSTAT classification

### ISSUE THREAD

**Issue by stevieflow** [OpenAgFunding/development#20]
From https://github.com/OpenAgFunding/development/issues/4

ACTIONS: accessing a full list of these classifications would enable us to determine that the codes are all unique (it appears to be the case)

**Comment by mbacou** [comment]
@stevieflow I added complete FAOSTAT product codes and 2 alternate groupings in the repo:
1. https://github.com/OpenAgFunding/development/blob/master/codelists/FAOSTAT-items%20(aggregates).csv
2. https://github.com/OpenAgFunding/development/blob/master/codelists/FAOSTAT-items.csv

I would suggest using the classification in 2) (that also includes agricultural inputs), but I noted that codes for fresh/cut flowers are missing, as well as codes for fisheries. Will take a look at what might be available for the 2 missing sectors, and update here.

**Comment by timgdavies** [comment]
Proposed classification in #4
