### ISSUE TITLE
Research how Policy Marker functions

### ISSUE THREAD

**Issue by stevieflow** [OpenAgFunding/development#23]
We can observe that the Humanitarian reporting addition to IATI includes some use of the Policy Marker function, by adding a [Vocabulary to the codelist](https://github.com/OpenAgFunding/development/issues/22#issuecomment-228207695) (although see: https://github.com/IATI/IATI-Codelists/issues/94 )

More widely, it is useful to understand how `policy-marker` works within the standard, as it has (to put it simply) **two** variables.  This - quite literally - means twice the "control" that a single sector classification has

(NB: policy marker codes are embedded  codelists, even though they are derived from OECD DAC sources (partly due to structural differences, I think)

These two _[variables](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/policy-marker/)_ are:
- code 
- significance

With the addition of a vocabulary attribute to override the OECD-DAC derived codelists - this could be of relevance for more complex Ag classifications, potentially

That is technically / structurally how things work.  More policy / user insight would be needed

**Comment by lgrino** [comment]
In case it's helpful at all, here is the [guidance from the DAC on policy markers](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/addenda-converged-statistical-reporting-directives.htm) (see annexes 17 and 18). Though the humanitarian extension seems to have made use of the policy marker, I don't think this is the best route for us to pursue (it would seem to impose a greater burden on publishers, who would need to refer to both an IATI and OECD DAC policy marker codelist).

**Comment by timgdavies** [comment]
Based on this research and feedback, we are not proposing use of policy-markers for OpenAgFunding.
