### ISSUE TITLE
extension - @ on attribute in documentation

### ISSUE THREAD

**Issue by stevieflow** [OpenAgFunding/development#35]
In the [documentation](http://openagfunding.readthedocs.io/en/latest/extensions/) we see:

![xml](https://user-images.githubusercontent.com/1209944/30688831-1f7ed3b8-9eb7-11e7-9bfa-8b1092f04710.png)

This includes a 

``@xml:lang`` - the @ character throws validation

In repo, I cant see this however: https://github.com/OpenAgFunding/development/blob/master/docs/extensions.md

Has something not been merged/pushed, perhaps?

**Comment by Bjwebb** [comment]
This was fixed in this commit https://github.com/OpenAgFunding/development/commit/9997c0ee355821ca57eadcc283b4ef3194f3bea4. And the build for that never finished: https://readthedocs.org/projects/openagfunding/builds/
I've triggered another build and it should be fixed shortly.

**Comment by Bjwebb** [comment]
Fixed now https://openagfunding.readthedocs.io/en/latest/extensions/#what-is-it

It's nice and colourful and everything.
